import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // AnchorID Design System – from Stitch mockups
        'surface-container-lowest': '#060e20',
        'surface-dim': '#0b1326',
        'surface-bright': '#31394d',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'surface-variant': '#2d3449',
        background: '#0b1326',
        surface: '#0b1326',
        primary: '#98cded',
        'primary-fixed': '#c3e8ff',
        'primary-fixed-dim': '#98cded',
        'primary-container': '#0a4d68',
        'on-primary': '#003549',
        'on-primary-fixed': '#001e2c',
        'on-primary-fixed-variant': '#084c67',
        'on-primary-container': '#88bddc',
        'inverse-primary': '#2c6480',
        secondary: '#5de6ff',
        'secondary-fixed': '#a2eeff',
        'secondary-fixed-dim': '#2fd9f4',
        'secondary-container': '#00cbe6',
        'on-secondary': '#00363e',
        'on-secondary-fixed': '#001f25',
        'on-secondary-fixed-variant': '#004e5a',
        'on-secondary-container': '#00515d',
        tertiary: '#4edea3',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'tertiary-container': '#005237',
        'on-tertiary': '#003824',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        'on-tertiary-container': '#37cd93',
        'on-background': '#dae2fd',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#c0c7cd',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
        outline: '#8a9297',
        'outline-variant': '#41484d',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'surface-tint': '#98cded',
        // Custom semantic tokens
        'glass-surface': 'rgba(255, 255, 255, 0.05)',
        'glass-border': 'rgba(255, 255, 255, 0.15)',
        'verified-glow': 'rgba(16, 185, 129, 0.3)',
        'cyan-glow': 'rgba(34, 211, 238, 0.15)',
        'data-label': '#94A3B8',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['10px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
        'data-mono': ['12px', { lineHeight: '1.4', fontWeight: '400' }],
      },
      spacing: {
        'card-padding': '20px',
        'section-gap': '32px',
        'stack-gap': '8px',
        'container-margin': '24px',
        gutter: '16px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      backdropBlur: {
        xs: '4px',
        sm: '8px',
        DEFAULT: '12px',
        md: '16px',
        lg: '24px',
        xl: '40px',
      },
      animation: {
        drift: 'drift 20s ease infinite alternate',
        'pulse-ring': 'pulseRing 3s cubic-bezier(0.4,0,0.6,1) infinite',
        'scan-line': 'scanLine 3s ease-in-out infinite',
        'fade-in': 'fadeIn 0.4s ease-out',
        'slide-up': 'slideUp 0.4s ease-out',
        'glow-pulse': 'glowPulse 2s ease-in-out infinite',
      },
      keyframes: {
        drift: {
          '0%': { transform: 'scale(1) rotate(0deg)' },
          '100%': { transform: 'scale(1.1) rotate(2deg)' },
        },
        pulseRing: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '50%': { opacity: '0.5' },
          '100%': { transform: 'scale(1.05)', opacity: '0' },
        },
        scanLine: {
          '0%, 100%': { top: '1.5rem', opacity: '0' },
          '10%, 90%': { opacity: '1' },
          '50%': { top: 'calc(100% - 1.5rem)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        glowPulse: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(93, 230, 255, 0.3)' },
          '50%': { boxShadow: '0 0 40px rgba(93, 230, 255, 0.6)' },
        },
      },
      boxShadow: {
        glass: '0 8px 32px 0 rgba(10, 77, 104, 0.15)',
        'glass-lg': '0 16px 64px 0 rgba(10, 77, 104, 0.2)',
        cyan: '0 8px 32px 0 rgba(34, 211, 238, 0.15)',
        'cyan-lg': '0 0 40px rgba(93, 230, 255, 0.3)',
        verified: '0 8px 32px 0 rgba(16, 185, 129, 0.15)',
        'verified-lg': '0 0 20px rgba(16, 185, 129, 0.2)',
      },
    },
  },
  plugins: [],
}

export default config
